### ISSUE TITLE
BuyItem function does not actually allow use of existing balance

### ISSUE THREAD

**Issue by Agreene** [etheremon/smartcontract#2]
In the buyItem function in EtheremonTrade.sol , the intention seems to be that users can pay through the combination of both ether they send directly and also their existing balance in the EtheremonData contract:
`uint256 totalBalance = safeAdd(msg.value, data.getExtraBalance(msg.sender));`

However, at the end of the function it tries to send the full price of the item, disregarding any amount that was already in the EtheremonData contract:
`// send money to etheremon world contract`
`worldContract.transfer(safeSubtract(requestPrice, requestPrice / tradingFeeRatio));`

This action will fail and throw an exception if the user did not send enough in the msg.value payload.  Which means that it doesn't actually matter how much money users have in the Data contract.

**Comment by Agreene** [comment]
The same issue is also present in the borrowItem function.

**Comment by etheremonnn** [comment]
thank you, fixed
